language: go
env: BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
matrix:
  include:
  - go: 1.12.x
    script:
    - mkdir $GOPATH/src/github.com/gini
    - mv $GOPATH/src/github.com/HealthEngineAU/dexter $GOPATH/src/github.com/gini
    - cd $GOPATH/src/github.com/gini/dexter
    - make vet
    - make test
    - OS=darwin make build
    - OS=windows make build
    - OS=linux make build
deploy:
  provider: s3
  bucket: $ARTIFACT_BUCKET
  file: build/*
  file_glob: true
  skip_cleanup: true
  region: ap-southeast-2
  local_dir: build
  upload-dir: dexter/$TRAVIS_BRANCH
  on:
    repo: HealthEngineAU/dexter
