language: go
env: BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
matrix:
  include:
  - go: 1.12.x
    script:
    - make vet
    - make test
    - OS=darwin make build
    - OS=windows make build
    - OS=linux make build
deploy:
  provider: s3
  bucket: $ARTIFACT_BUCKET
  file: build/*
  file_glob: true
  skip_cleanup: true
  upload-dir: dexter/$TRAVIS_BRANCH
  on:
    repo: healthengineau/dexter
    tags: true
